---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1mf7prq4pd8p5n42tz4e8tkrdka2p20yvx3zk9n2qlnrsm2cl0eds78w2sj
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1mf7prq4pd8p5n42tz4e8tkrdka2p20yvx3zk9n2qlnrsm2cl0eds78w2sj
