# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:D9uOmNG7uT15eJMeOXEki+wn,iv:sFEXxxah897Fst/c+4f+DpEoSvYel/Yx2ov4wONuWmo=,tag:QlztkdWbapkB44J2tzt16w==,type:str]
    api-key: ENC[AES256_GCM,data:KBWDNpHMh82yGsfAhqJ7B7tsLzlchI/gVqzaayS1wvrncjr5ug==,iv:fseqd6GdOF3pF24HCotfpmDe9bDoRYH2f7XiNjUd9Is=,tag:OhLXs3hMCdF7NsvGT/xePQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mf7prq4pd8p5n42tz4e8tkrdka2p20yvx3zk9n2qlnrsm2cl0eds78w2sj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZzhwRXZFRTlXM1Q3V2lN
            MzlzN1hhL2cvY2ZJYnovVERMclZqT1FxNWxFClExd1FXbFYzWGVuSk5wdmY2TE1J
            bDl5TGU4N3VyVTVEdFFMNncrSmxwMlEKLS0tIGZnTUJ0ekFPdzV0TWs2d2VNM2xI
            TFZuRDRkMDRrcldZTmhHVm82MHhWNWcKrdsV44me1UGkkqXgppNLso93YsYWw6vJ
            czGdWDbxHoLbHaPNRZdgMWv3WVRd95GLGp6WqPh2pD3EDY8VrcfQiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-17T06:36:33Z"
    mac: ENC[AES256_GCM,data:7ovOxY3RFrftM/H5gff3cOJGlsfjV7YG4q2Upp99pHuLVfSUgC3fe/CayJtA5F5Mw3trgDI7Bg5B1abfaIMwxVqHw2JI8k3ujquu0txdhkdq7fZ+pjNR3LHazuiZ2AY3aUVziGgVIFpWGGvEwZZuHgItHila/9SSm5+8ZavjUI4=,iv:8j1fiiQYEDcr3Pe0todNhJ+drLaCACcYlDncXi7U2Zo=,tag:yqLqe+dPMh/ui7j+nq4dWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
